var q_content = [{
    course_name: "Math",
    data: [{
        date: "2020 3 17",
        course: "Math",
        title: "Angles",
        marks: "",
        comments: "",
        submission_date: "",
        submitted: false,
        reviewed: false,
        publisher: "Zhao",
        dueDate: "2020 4 1",
        id: 0,
        book_img_url: "/images/books/math.png",
        detail: "1. cos(π/2)+sin(π/2)=    2.sin(π/3)+tan(π/3)=    3.sin(π/3)xcos(4π/3)=   4. read text book from page 40 to page 50",
      },
      {
        date: "2020 3 17",
        course: "Math",
        title: "Geometry",
        marks: "",
        comments: "",
        submission_date: "",
        submitted: false,
        reviewed: false,
        publisher: "Zhao",
        dueDate: "2020 5 1",
        id: 1,
        book_img_url: "/images/books/math.png",
        detail: "1. cos(π/2)+sin(π/2)=    2.sin(π/3)+tan(π/3)=    3.sin(π/3)xcos(4π/3)=   4. read text book from page 50 to page 70",
      },
      {
        date: "2020 4 17",
        course: "Math",
        title: "Eclipse",
        marks: "",
        comments: "",
        submission_date: "",
        submitted: false,
        reviewed: false,
        publisher: "Zhao",
        dueDate: "Feb 20 2020",
        id: 2,
        book_img_url: "/images/books/math.png",
        detail: "y1: x²/16+y²/25=1, y2: y=5/4x. Please find the coordinates of the intersection of two functions on a rectangular coordinate system.",
      },
      {
        date: "2020 3 17",
        course: "Math",
        title: "Angles",
        marks: "9.9",
        comments: "excellent",
        submission_date: "",
        submitted: true,
        reviewed: false,
        publisher: "Zhao",
        dueDate: "2020 4 1",
        id: 3,
        book_img_url: "/images/books/math.png",
        detail: "1. cos(π/2)+sin(π/2)=    2.sin(π/3)+tan(π/3)=    3.sin(π/3)xcos(4π/3)=   4. read text book from page 40 to page 50",
      },
      {
        date: "2020 3 17",
        course: "Math",
        title: "Geometry",
        marks: "9.1",
        comments: "good",
        submission_date: "",
        submitted: true,
        reviewed: true,
        publisher: "Zhao",
        dueDate: "2020 5 1",
        id: 4,
        book_img_url: "/images/books/math.png",
        detail: "1. cos(π/2)+sin(π/2)=    2.sin(π/3)+tan(π/3)=    3.sin(π/3)xcos(4π/3)=   4. read text book from page 50 to page 70",
      },
      {
        date: "2020 4 17",
        course: "Math",
        title: "Eclipse",
        marks: "8.4",
        comments: "normal",
        submission_date: "",
        submitted: true,
        reviewed: true,
        publisher: "Zhao",
        dueDate: "Feb 20 2020",
        id: 5,
        book_img_url: "/images/books/math.png",
        detail: "y1: x²/16+y²/25=1, y2: y=5/4x. Please find the coordinates of the intersection of two functions on a rectangular coordinate system.",
      },
    ]
  },
  {
    course_name: "Physics",
    data: [{
        date: "2020 3 14",
        course: "Physics",
        title: "Newtonian mechanics",
        marks: "",
        comments: "",
        submission_date: "",
        submitted: false,
        reviewed: false,
        publisher: "Zhu",
        dueDate: "Jan 31 2020",
        id: 6,
        book_img_url: "/images/books/physics.png",
        detail: "Suppose there is an object on a smooth plane. At the moment t0 = 0s, the initial velocity v0 is 1m/s and the acceleration is a constant a = 1.5m/s². Find how far away from the initial position after 5 seconds.",
      },
      {
        date: "2020 3 14",
        course: "Physics",
        title: "Newtonian mechanics",
        marks: "7.2",
        comments: "not bad",
        submission_date: "",
        submitted: true,
        reviewed: false,
        publisher: "Zhu",
        dueDate: "Jan 31 2020",
        id: 7,
        book_img_url: "/images/books/physics.png",
        detail: "Suppose there is an object on a smooth plane. At the moment t0 = 0s, the initial velocity v0 is 1m/s and the acceleration is a constant a = 1.5m/s². Find how far away from the initial position after 5 seconds.",
      }
    ]
  },
  {
    course_name: "History",
    data: [{
      date: "2020 3 14",
      course: "History",
      title: "World War II",
      marks: "",
      comments: "",
      submission_date: "",
      submitted: false,
      reviewed: false,
      publisher: "Wang",
      dueDate: "Mar 1 2020",
      id: 8,
      book_img_url: "/images/books/history.png",
      detail: "1. When did WW2 start?    2. When did the war end?   3. Read text book from page 65 to page 85",
    }, ]
  },
  {
    course_name: "Chemistry",
    data: [
      {
        date: "Feb 24 2020",
        course: "Chemistry",
        title: "Chemical Equation",
        marks: "",
        comments: "",
        submission_date: "",
        submitted: false,
        reviewed: false,
        publisher: "Chen",
        dueDate: "Feb 28 2020",
        id: 9,
        book_img_url: "/images/books/chemistry.png",
        detail: "1. Cu(OH)2 + H2SO4 = ??  2.CaCO3 + NaOH = ??  3. Read text book from page 40 to page 50",
      },
    ]
  },
  



]

var s_h_content = [{
    course: "Math",
    data: {
      date: "2020 3 17",
      course: "Math",
      title: "Angles",
      marks: "9.9",
      comments: "excellent",
      submission_date: "",
      submitted: true,
      reviewed: false,
      publisher: "Zhao",
      dueDate: "2020 4 1",
      id: 0,
      book_img_url: "/images/books/math.png",
      detail: "1. cos(π/2)+sin(π/2)=    2.sin(π/3)+tan(π/3)=    3.sin(π/3)xcos(4π/3)=   4. read text book from page 40 to page 50",
    }
  },
  {
    course: "Math",
    data: {
      date: "2020 3 17",
      course: "Math",
      title: "Geometry",
      marks: "9.1",
      comments: "good",
      submission_date: "",
      submitted: true,
      reviewed: true,
      publisher: "Zhao",
      dueDate: "2020 5 1",
      id: 1,
      book_img_url: "/images/books/math.png",
      detail: "1. cos(π/2)+sin(π/2)=    2.sin(π/3)+tan(π/3)=    3.sin(π/3)xcos(4π/3)=   4. read text book from page 50 to page 70",
    }
  },
  {
    course: "Math",
    data: {
      date: "2020 4 17",
      course: "Math",
      title: "Eclipse",
      marks: "8.4",
      comments: "normal",
      submission_date: "",
      submitted: true,
      reviewed: true,
      publisher: "Zhao",
      dueDate: "Feb 20 2020",
      id: 2,
      book_img_url: "/images/books/math.png",
      detail: "y1: x²/16+y²/25=1, y2: y=5/4x. Please find the coordinates of the intersection of two functions on a rectangular coordinate system.",
    }
  },
  {
    course: "Physics",
    data: {
      date: "2020 3 14",
      course: "Physics",
      title: "Newtonian mechanics",
      marks: "7.2",
      comments: "not bad",
      submission_date: "",
      submitted: true,
      reviewed: false,
      publisher: "Zhu",
      dueDate: "Jan 31 2020",
      id: 3,
      book_img_url: "/images/books/physics.png",
      detail: "Suppose there is an object on a smooth plane. At the moment t0 = 0s, the initial velocity v0 is 1m/s and the acceleration is a constant a = 1.5m/s². Find how far away from the initial position after 5 seconds.",
    }
  },
]

var assignments_content = [{
  data: 1
}]



module.exports = {
  q_List: q_content,
  // s_h_List: s_h_content,
}